name: Secret Scan
on:
  workflow_call:
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:

     # Gitleaks Scanning
     
      - uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v1
        env:
           GITLEAKS_EXIT_CODE: 1

# Add SARIF upload to GitHub Security tab
      - name: Upload Gitleaks SARIF
        uses: github/codeql-action/init@v4
        with:
           languages: python
      - name: sarif file auto upload    
        uses: github/codeql-action/analyze@v4
    
        # TRUFFLEHOG Scanning
        
      - name: Run TruffleHog Scan
        uses: trufflesecurity/trufflehog@v3.82.8
        with:
           path: ./
           base: ${{ github.event.before }}
           head: ${{ github.sha }}  
           
