name: Code linting
on:
  workflow_call:
   secrets:
      SONAR_TOKEN:
        required: true

env:
  PYTHON_VERSION: '3.12.3'

jobs:
  linting:
    name: Detect style and basic syntax issues
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest django pytest-django coverage 
        pip install flake8 pylint ruff

    - name: Run Flake8 (Linting)
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # Advanced Linter - Very strict code quality + design checks
    - name: Run Pylint
      run: pylint **/*.py --exit-zero

     # Fast Linter or Formatter Replaces Flake8 + isort + many plugins
    - name: Run Ruff (Lint + Import Check)
      run: ruff check . --fix  
    
    - name: Show repo structure
      run: ls -R     
    
    - name: Run tests with coverage
      run: |
          coverage run manage.py test
          coverage xml
    
      # SonarCloud Scan for code quality
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
          args: >
            -Dsonar.projectKey=anisur81_portfolio
            -Dsonar.organization=anisur81
            -Dsonar.python.coverage.reportPaths=coverage.xml       
