name: Image Scan
on:
  workflow_call:

jobs:
  trivy:
    name: Image scan with Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@v0.35.0
        with:
           scan-type: image
           image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }}
           format: sarif
           output: trivy-image.sarif

      - name: Upload Trivy Scan Results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
           sarif_file: trivy-image.sarif
